---

- name: Upgrade nodes
  hosts: nodes
  become: true
  gather_facts: false
  tasks:
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: safe

...
