---

- name: Sudo user
  hosts: nodes
  become: true
  gather_facts: false
  vars:
    sudo_user: planx
  tasks:
    - name: Add sudo user
      ansible.builtin.user:
        name: "{{ sudo_user }}"
        groups: sudo
        append: true
        shell: /bin/bash
        state: present

    - name: Make sudo without password for user
      ansible.builtin.lineinfile:
        path: "/etc/sudoers.d/80-ansible-sudo-user"
        state: present
        regexp: "{{ sudo_user }} ALL="
        line: "{{ sudo_user }} ALL=(ALL) NOPASSWD: ALL"
        validate: "/usr/sbin/visudo -cf %s"

    - name: Set authorized key from file
      ansible.posix.authorized_key:
        user: "{{ sudo_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
...
