---

- name: Users
  hosts: nodes
  become: true
  gather_facts: false
  tasks:
    - name: Create user
      ansible.builtin.user:
        name: "{{ user1 }}"
        password: "{{ user1_pass | string | password_hash('sha512') }}"
        groups: sudo
        append: true
        shell: /bin/bash
        state: present

    - name: Set authorized key from file
      ansible.posix.authorized_key:
        user: "{{ user1 }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
...
